### PR TITLE
merge upstream

### PR DESCRIPTION
**Pull request by pdavid0**
#### JIRA
https://buscom.atlassian.net/browse/BANA-3856

#### Dev notes
+ Changed the branch name so that it's testable from a # url aka 
https://github.com/Bus-com/heroku-buildpack-monorepo-with-shared-gems#fix-heroku-20

### CODE REVIEW

**Comment by edmorley** [comment]
@pdavid0 Hi! I'm on the team that maintains Heroku's build system and official buildpacks. I just wanted to check in and see when this compatibility fix might be merged? We would like to make the change to Heroku's build system that will break buildpacks that don't have the fixes within this PR very soon, so would recommend merging this sooner rather than later.

Also just to clarify, contrary to this PR's title, the compatibility fixes made to the upstream buildpack are not for Heroku-20 support but due to the reasons mentioned in:
https://github.com/lstoll/heroku-buildpack-monorepo/issues/12

**Comment by pdavid0** [comment]
@edmorley Thanks for dropping a line ! 

I'll get my team to prioritize the update in the next sprint.

**Comment by edmorley** [comment]
@pdavid0 Great - thank you :-)

**Comment by edmorley** [comment]
@pdavid0 Hi! Any news on this?

**Comment by pdavid0** [comment]
@edmorley Done.

**Comment by edmorley** [comment]
Thank you :-)

**Pull request merged**
