### PR TITLE
chore(monorepo): support heroku-20

### PR DESCRIPTION
**Pull request by pdavid0**
#### JIRA: 
https://buscom.atlassian.net/browse/BANA-3856

### CODE REVIEW

**Review by francois — APPROVED** [review]
I hope this won't make it's way directly in production? Does lstoll's repo have the corresponding change? Can we merge their change instead?

**Comment by francois** [comment]
@pdavid0 https://github.com/lstoll/heroku-buildpack-monorepo/commit/82e175c304f943b2c6d4083a085083ebae5cdd61

We're missing "shopt dotglob"

**Comment by francois** [comment]
I'd say cherry-pick that commit instead of building a new one?

**Comment by pdavid0** [comment]
Ok thanks

**Comment by pdavid0** [comment]
@francois done, ill squash the commit at merge time.

**Review by Zelnox — APPROVED** [review]
We still have to click the EZ button in Heroku right?

**Pull request closed without merging**
